export const JonesList = [
  { name: "FORD, JIM", bgc: "#FEE2E2", borderTop: "#FCA5A5" },
  { name: "ADAMS, MARIE J", bgc: "#E0F2FE", borderTop: "#7DD3FC" },
  { name: "CAMPBELL, LISA C", bgc: "#FEF3C7", borderTop: "#FCD34D" },
  { name: "HANSBERRY, BETTY", bgc: "#EDE9FE", borderTop: "#C4B5FD" },
  { name: "ROBINSON, TRACIE", bgc: "#FAE8FF", borderTop: "#F5D0FE" },
  { name: "HUGHES, JIM", bgc: "#FFEDD5", borderTop: "#FDBA74" },
  { name: "STOLFUS, LINDSAY", bgc: "#DCFCE7", borderTop: "#86EFAC" },
  { name: "JONES, BOB", bgc: "#F1F5F9", borderTop: "#CBD5E1" },
  { name: "BRADFORD, JIM", bgc: "#FEE2E2", borderTop: "#FCA5A5" },
  { name: "MILLER, SARAH", bgc: "#ECFEFF", borderTop: "#67E8F9" },
  { name: "WILSON, DAVID", bgc: "#E0E7FF", borderTop: "#A5B4FC" },
  { name: "GARCIA, MARIA", bgc: "#FDF2F8", borderTop: "#F9A8D4" },
  { name: "MARTINEZ, KEVIN", bgc: "#F5F3FF", borderTop: "#DDD6FE" },
  { name: "RODRIGUEZ, ANA", bgc: "#FFFBEB", borderTop: "#FDE68A" },
  { name: "LEE, JUN", bgc: "#F0FDF4", borderTop: "#BBF7D0" },
  { name: "WALKER, CHRIS", bgc: "#EFF6FF", borderTop: "#BFDBFE" },
  { name: "YOUNG, AMY", bgc: "#FAF5FF", borderTop: "#E9D5FF" },
  { name: "HERNANDEZ, LU", bgc: "#FFF7ED", borderTop: "#FFEDD5" },
  { name: "KING, ROBERT", bgc: "#F8FAFC", borderTop: "#E2E8F0" },
  { name: "WRIGHT, EMMA", bgc: "#F0FDFA", borderTop: "#99F6E4" },
  { name: "LOPEZ, JORGE", bgc: "#FFF1F2", borderTop: "#FECDD3" },
  { name: "HILL, REBECCA", bgc: "#F0F9FF", borderTop: "#BAE6FD" },
  { name: "SCOTT, ALAN", bgc: "#F5F3FF", borderTop: "#C4B5FD" }
];

export const MillerList = [
  { name: "BAKER, TINA", bgc: "#E0F2FE", borderTop: "#7DD3FC" },
  { name: "CARTER, BILL", bgc: "#F0FDFA", borderTop: "#99F6E4" },
  { name: "DAVIS, MEGAN", bgc: "#FEE2E2", borderTop: "#FCA5A5" },
  { name: "EVANS, GREG", bgc: "#F5F3FF", borderTop: "#C4B5FD" },
  { name: "FOSTER, LILY", bgc: "#FEF3C7", borderTop: "#FCD34D" },
  { name: "GREEN, MARK", bgc: "#DCFCE7", borderTop: "#86EFAC" },
  { name: "HARRIS, ZOE", bgc: "#FDF2F8", borderTop: "#F9A8D4" },
  { name: "IRWIN, JAKE", bgc: "#F1F5F9", borderTop: "#94A3B8" },
  { name: "JAMES, RUTH", bgc: "#DBEAFE", borderTop: "#93C5FD" },
  { name: "KELLY, SEAN", bgc: "#F8FAFC", borderTop: "#CBD5E1" },
  { name: "LEWIS, FAYE", bgc: "#FFF7ED", borderTop: "#FDBA74" },
  { name: "MORGAN, TIM", bgc: "#EDE9FE", borderTop: "#A78BFA" },
  { name: "NELSON, PAT", bgc: "#ECFDF5", borderTop: "#6EE7B7" },
  { name: "OWENS, KYLE", bgc: "#FAE8FF", borderTop: "#E879F9" },
  { name: "PEREZ, ROSA", bgc: "#FFF1F2", borderTop: "#FB7185" },
  { name: "QUINN, MARY", bgc: "#E0F7FA", borderTop: "#4DD0E1" },
  { name: "REED, BRIAN", bgc: "#FAFAFA", borderTop: "#D4D4D4" },
  { name: "SMITH, JOHN", bgc: "#EEF2FF", borderTop: "#818CF8" },
  { name: "TAYLOR, JO", bgc: "#FAF5FF", borderTop: "#D8B4FE" }
];

export const RicheyList = [
  { name: "UPTON, NEIL", bgc: "#FFFDE7", borderTop: "#FFF176" },
  { name: "VANCE, VICKY", bgc: "#E8F5E9", borderTop: "#A5D6A7" },
  { name: "WARD, STEVEN", bgc: "#E3F2FD", borderTop: "#90CAF9" },
  { name: "XU, XIAO", bgc: "#F3E5F5", borderTop: "#CE93D8" },
  { name: "YATES, CHAD", bgc: "#FCE4EC", borderTop: "#F48FB1" },
  { name: "ZANE, KELLY", bgc: "#FFEBEE", borderTop: "#EF9A9A" },
  { name: "ABBOTT, BEN", bgc: "#E0F2F1", borderTop: "#80CBC4" },
  { name: "BISHOP, ANN", bgc: "#E1F5FE", borderTop: "#81D4FA" },
  { name: "COOK, PETER", bgc: "#ECEFF1", borderTop: "#B0BEC5" },
  { name: "DRAKE, JILL", bgc: "#FFF3E0", borderTop: "#FFCC80" },
  { name: "ELLIS, TOBY", bgc: "#FDF2F8", borderTop: "#F9A8D4" },
  { name: "FINCH, ROSE", bgc: "#EDE7F6", borderTop: "#B39DDB" },
  { name: "GATES, BILL", bgc: "#E0F7FA", borderTop: "#80DEEA" },
  { name: "HOLMES, S.", bgc: "#FFEBEE", borderTop: "#FFAB91" },
  { name: "IVES, CAROL", bgc: "#FFFDE7", borderTop: "#FFE082" },
  { name: "JADE, ANNA", bgc: "#E8F5E9", borderTop: "#C8E6C9" },
  { name: "KENT, CLARK", bgc: "#E3F2FD", borderTop: "#BBDEFB" },
  { name: "LANE, Lois", bgc: "#FCE4EC", borderTop: "#F8BBD0" },
  { name: "MOORE, GENE", bgc: "#F5F5F5", borderTop: "#CFD8DC" },
  { name: "NASH, NASH", bgc: "#FFF8E1", borderTop: "#FFE082" },
  { name: "ORION, RAY", bgc: "#E1F5FE", borderTop: "#B3E5FC" }
];

export const TracyList = [
  { name: "POPE, ALICE", bgc: "#F3E5F5", borderTop: "#D1C4E9" },
  { name: "QUARTZ, TY", bgc: "#E0F2F1", borderTop: "#B2DFDB" },
  { name: "RICE, DONNA", bgc: "#FFEBEE", borderTop: "#FFCDD2" },
  { name: "STONE, MICK", bgc: "#E8EAF6", borderTop: "#C5CAE9" },
  { name: "TRENT, GARY", bgc: "#E8F5E9", borderTop: "#C8E6C9" },
  { name: "UNDER, KIM", bgc: "#FFF3E0", borderTop: "#FFE0B2" },
  { name: "VALE, JERRY", bgc: "#E1F5FE", borderTop: "#B3E5FC" },
  { name: "WATT, JAMES", bgc: "#FFFDE7", borderTop: "#FFF9C4" },
  { name: "XAVIER, F.", bgc: "#FCE4EC", borderTop: "#F8BBD0" }
];

export const NurseEastList = [
  { name: "YORK, TERRY", bgc: "#E0F7FA", borderTop: "#B2EBF2" },
  { name: "ZIGGY, STARD", bgc: "#F3E5F5", borderTop: "#E1BEE7" },
  { name: "ALVA, MARIE", bgc: "#FFEBEE", borderTop: "#F8BBD0" },
  { name: "BOND, JAMES", bgc: "#E8F5E9", borderTop: "#C8E6C9" },
  { name: "CREW, TERRY", bgc: "#EDE7F6", borderTop: "#D1C4E9" },
  { name: "DIAZ, CAMI", bgc: "#FFF3E0", borderTop: "#FFE0B2" },
  { name: "EARL, JUSTIN", bgc: "#E0F2F1", borderTop: "#B2DFDB" },
  { name: "FLINT, CAPT", bgc: "#FFEBEE", borderTop: "#FFCDD2" },
  { name: "GAGE, FRED", bgc: "#E8EAF6", borderTop: "#C5CAE9" },
  { name: "HOPE, BOBBY", bgc: "#ECEFF1", borderTop: "#CFD8DC" },
  { name: "ISAAC, NEWT", bgc: "#F3E5F5", borderTop: "#E1BEE7" },
  { name: "JOBS, STEVE", bgc: "#FFFDE7", borderTop: "#FFF9C4" },
  { name: "KLINE, OTTO", bgc: "#E8F5E9", borderTop: "#A5D6A7" },
  { name: "LONG, BARRY", bgc: "#FCE4EC", borderTop: "#F48FB1" },
  { name: "MARS, BRUNO", bgc: "#E3F2FD", borderTop: "#BBDEFB" },
  { name: "NORI, KENJI", bgc: "#E8F5E9", borderTop: "#A5D6A7" },
  { name: "OPAL, GWEN", bgc: "#FFF3E0", borderTop: "#FFE0B2" },
  { name: "PARK, LINDA", bgc: "#ECEFF1", borderTop: "#CFD8DC" },
  { name: "QUICK, FAST", bgc: "#E8EAF6", borderTop: "#C5CAE9" }
];